---
global:
  scrape_interval: "5s"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets:
          - "localhost:9090"

  - job_name: "ui"
    static_configs:
      - targets:
          - "ui:8000"

  - job_name: "crawler"
    static_configs:
      - targets:
          - "crawler:8000"

  - job_name: "node"
    static_configs:
      - targets:
          - "node-exporter:9100"

  - job_name: "mongodb"
    static_configs:
      - targets:
          - "mongodb-exporter:9216"

  - job_name: "rabbitmq"
    static_configs:
      - targets:
          - "rabbitmq:15692"

  - job_name: "blackbox"
    metrics_path: /metrics
    params:
      module: [http_200_check]
    static_configs:
      - targets:
          - "http://ui:8000"
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115
